### PR TITLE
[main][feat] Merge Defillama/main to alpaca/defillama-adapters

### PR DESCRIPTION
**Pull request by m100alpaca**
**NOTE**

> - If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
> - If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1. Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2. Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3. The protocol is usually listed within 24 hours of merging the PR
4. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
5. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
6. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
7. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/alpaca-finance-lend: 
        
 
  
    
    
    TypeError: getProcolAddresses is not a function
    Truncated error stack:
    
        at tvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/alpaca-finance-lend/lend.js:7:27)
        at getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:52:29)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:148:15
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:136:29
        at Array.map (<anonymous>)
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:131:44

**Comment by llamatester** [comment]
The adapter at projects/alpaca-finance-lend exports TVL: 
        
 
 
    fantom-borrowed           497.65 k
    fantom                    1.14 M
    bsc                       160.03 M
    bsc-borrowed              107.37 M
    borrowed                  107.86 M
    
    total                    161.16 M

**Comment by llamatester** [comment]
The adapter at projects/alpaca-finance exports TVL: 
        
 
 
    fantom-staking            271.50 k
    bsc-staking               11.68 M
    fantom                    968.03 k
    bsc                       168.80 M
    staking                   11.95 M
    
    total                    169.77 M

**Review by jr-alpaca — APPROVED** [review]

**Comment by llamatester** [comment]
The adapter at projects/alpaca-finance-lend exports TVL: 
        
 
 
    bsc-borrowed              107.25 M
    fantom                    1.14 M
    fantom-borrowed           497.51 k
    bsc                       161.00 M
    borrowed                  107.74 M
    
    total                    162.13 M

**Comment by llamatester** [comment]
The adapter at projects/alpaca-finance exports TVL: 
        
 
 
    fantom-staking            271.55 k
    bsc-staking               11.68 M
    fantom                    967.75 k
    bsc                       168.38 M
    staking                   11.95 M
    
    total                    169.35 M

**Comment by llamatester** [comment]
The adapter at projects/alpaca-finance-v2 exports TVL: 
        
 
 
    bsc-borrowed              14.66 M
    bsc                       20.20 M
    borrowed                  14.66 M
    
    total                    20.20 M

**Pull request merged**
